# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=4)),
                ('quantity', models.CharField(max_length=4)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(default='images/default/no-img.jpg', upload_to='images/')),
            ],
        ),
    ]
