# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-15 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0002_remove_adds_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='mydata',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=4, null=True),
        ),
    ]
