# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0003_adds_mydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='mydata',
            field=models.CharField(choices=[('Broilers', 'Broilers'), ('Layers', 'Layers'), ('Eggs', 'Eggs')], max_length=5, null=True),
        ),
    ]
