# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-15 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0004_auto_20161115_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adds',
            old_name='mydata',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='adds',
            name='add_title',
        ),
    ]
