# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-15 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0006_auto_20161115_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='address',
            field=models.CharField(choices=[('Ghana Hola', 'Mikindani-Gahana Hola'), ('Kwashee', 'Mikindani- Kwashee'), ('Kwa Mwanzia', 'Mikindani- Kwa Mwanzia'), ('Staff', 'Mikindani- Staff'), ('Alidina', 'Mikindani- Alidina')], max_length=50),
        ),
    ]
