# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-16 12:56
from __future__ import unicode_literals

import Adds.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0009_auto_20161116_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('image', models.ImageField(upload_to=Adds.models.image_upload_to)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adds.Adds')),
            ],
        ),
    ]
