# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0014_auto_20161116_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
