# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0015_auto_20161123_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='choose_category',
            field=models.CharField(choices=[('Broilers', 'Broilers'), ('Layers', 'Layers'), ('Kenbro', 'Kenbro'), ('Kienyeji', 'Kienyeji'), ('Hybreed', 'Hybreed'), ('Kuroiler', 'Kuroiler'), ('Rainbow Rooster', 'Rainbow Rooster'), ('Chicken Feed', 'Chicken Feed'), ('Eggs', 'Eggs')], max_length=50, null=True),
        ),
    ]
