# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-24 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adds', '0016_auto_20161123_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adds',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adds',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='adds',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='adds',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
